import React from "react";
import Head from 'next/head';
import styles from '../../../styles/page.module.css'
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import Button from '@mui/material/Button';
import Link from '@mui/material/Link';
import TextField from '@mui/material/TextField';
import List from '@mui/material/List';
import Typography from '@mui/material/Typography';

function Index () {
    return (
        <main>
            <Head>
                <title>Login | User List</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/icons/pavicon.png" width={10} height={10}/>
            </Head>
            <Box
                sx={{
                    flexGrow: 1
                }}
                className={styles.loginBoxStyle}>
                <Grid container="container">
                    <Grid item="item" xs={7}>
                        <Box className={styles.textLoginStyle}>
                            <Typography className={styles.titleLoginStyle} gutterBottom>
                                Lorem Ipsum
                            </Typography>
                            <Typography className={styles.subtitleLoginStyle} gutterBottom>
                                Lorem ipsum dollor sit ammet consentratt perendium das liederscaht.
                            </Typography>
                        </Box>
                    </Grid>
                    <Grid item="item" xs={5}>
                        <Box component="form" autoComplete="off" className={styles.loginBoxInputStyle}>
                            <TextField
                                id="input-with-sx"
                                label="Email"
                                variant="outlined"
                                className={styles.loginEmailStyle}/>
                           <TextField
                                id="input-with-sx"
                                label="Password"
                                variant="outlined"
                                className={styles.loginPasswordStyle}/>
                            <List>
                                <Button variant="contained" className={styles.loginButtonStyle}>Login</Button>
                                <Link href="#" underline="none" className={styles.forgotPasswordStyle}>
                                    Forgot Password ?
                                </Link>
                            </List>
                        </Box>
                    </Grid>
                </Grid>
            </Box>
        </main>
    );
}

export default Index;