import React, { useState } from 'react';
import PropTypes from 'prop-types';
import Head from 'next/head';
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';
import styles from '../styles/page.module.css'
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import IconButton from '@mui/material/IconButton';

import PeopleAltIcon from '@mui/icons-material/PeopleAlt';
import MailLockIcon from '@mui/icons-material/MailLock';
import SyncIcon from '@mui/icons-material/Sync';
import AddTaskIcon from '@mui/icons-material/AddTask';
import MoreVertIcon from '@mui/icons-material/MoreVert';
import SyncAltIcon from '@mui/icons-material/SyncAlt';
import ArrowCircleDownIcon from '@mui/icons-material/ArrowCircleDown';
import ArrowCircleUpIcon from '@mui/icons-material/ArrowCircleUp';
import AccountBalanceWalletIcon from '@mui/icons-material/AccountBalanceWallet';
import ContactlessIcon from '@mui/icons-material/Contactless';
import AlarmOnIcon from '@mui/icons-material/AlarmOn';
import AlarmOffIcon from '@mui/icons-material/AlarmOff';

import Image from 'next/image'

function Index (props) {

  return (

    <main>
        <Head>
            <title>Dahboard | User List</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/icons/pavicon.png" width={10} height={10}/>
        </Head>
        <Box sx={{ display: 'flex' }}>
            <CssBaseline />
              <Typography>Halo</Typography>
        </Box>
    </main>
  );
}

Index.propTypes = {
  window: PropTypes.func,
};

export default Index;